### ISSUE TITLE
[Issue] Update Docs/Example for 'mattermost_database_at_rest_key'

### ISSUE THREAD

**Issue by armenr** [pieterlexis/ansible-role-mattermost#4]
Greetings - thank you for such a useful and complete mattermost role. You've done excellent work!

I gave it a quick demo run, and was bitten by:
```
TASK [project.mattermost : Configure the database] ******************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'mattermost_database_at_rest_key' is undefined"}
```

It seems that the var Ansible is expecting to interpolate is referenced in the key/value config here:
[config.yml - line 19](https://github.com/pieterlexis/ansible-role-mattermost/blob/e1dade2aa2f2e8b45a7e0cc624e2e230eee61f73/tasks/config.yml#L19)

I think it might be useful to update your example/documentation to reflect that this is a required variable.

If this is intentional, then please feel free to close this issue. Thank you again!

**Comment by rei-ifesca** [comment]
This patch fixes the problem with the missing rest key variable ;)
